# Automatically generated by configure - do not modify
TARGET_NAME=x86_64
target=x86_64-softmmu
CONFIG_SOFTMMU=y
QEMU=/home/lee/Desktop/ACE-Analog-Cell-Emulator/femu/build-femu/qemu-system-x86_64
CROSS_CC_GUEST_CFLAGS=-m64
CROSS_CC_GUEST_STATIC=y
CROSS_CC_GUEST=cc
