# Automatically generated by configure - do not modify
SRC_PATH=/home/lee/Desktop/ACE-Analog-Cell-Emulator/femu/roms/seabios
AS=as
CCAS=cc
CC=cc
BCC=bcc
CPP=cc -E
OBJCOPY=objcopy
IASL=iasl
LD=ld
RANLIB=ranlib
